export const EMPLOYEES = [
  {
    name: "Agron Kabashi",
    email: "agron.kabashi@1337.tech",
    phoneNumber: "+46725133736",
    office: "Lund",
    manager: "lotta.wennolf@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>I have been working in the software industry for over 10 years now, and even though the road has been bumpy, I don’t regret a single second of it! My experiences have been quite varied, from creating games to full blown web-based intranet platforms.</p><p>Because of this variation and these experiences I’ve found that I’ve acquired a thirst for front-end development and anything web related, which can range from mobile apps to web-based SaaS solutions. The fact that you can create ANYTHING with almost nothing is an exhilarating feeling. It’s one of the major reasons that keeps me going; the only limit is my imagination.</p><p>I absolutely love to travel and experience new cultures (and food!) when the opportunity presents itself. My goal in life is to visit as many places and experience as many different cultures as I possibly can. So far I can cross off Europe and half of Asia from my list, and I look forward to many more exciting adventures to come.</p>  ",
    gitHub: "AgronKabashi",
    twitter: "_agronkabashi",
    stackOverflow: null,
    linkedIn: "/pub/agron-kabashi/54/6a8/4a6",
    imagePortraitUrl: "https://i.1337co.de/profile/agron-kabashi",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/agron-kabashi",
    highlighted: false,
    published: true
  },
  {
    name: "Marsel Mutlak",
    email: "marsel.mutlak@1337.tech",
    phoneNumber: "+46725133724",
    office: "Stockholm",
    manager: "karl.ecstrom@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>Do you remember that feeling you got during your childhood when you got acquainted with your first device, computer or game console and you got that WOW feeling? In my case, that feeling grew into a love for the development of these devices and they still give me that WOW feeling each time I develop something new.</p><p>Currently, my main focus is on mobile development, based on Xamarin, which I consider to be one of the foremost cross platform tools - it could make the future easier in our pockets.</p><p>I'm always open to learning new things in programming, and that's what is so exciting about this branch - there is something new every day.</p><p>In my spare time, I like to do some exercise, visit my friends and play video games to get that WOW feeling! </p> ",
    gitHub: "marsel-mo",
    twitter: "marsel_moo",
    stackOverflow: "9257345",
    linkedIn: "/in/marsel-mutlak/",
    imagePortraitUrl: "https://i.1337co.de/profile/marsel-mutlak",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/marsel-mutlak",
    highlighted: false,
    published: true
  },
  {
    name: "Rok Horvat",
    email: "rok.horvat@1337.tech",
    phoneNumber: "+38640504663",
    office: "Ljubljana",
    manager: "biserka.cvetkovska@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>I started my professional path as a graphic designer, but soon found out that designing for web and devices is what I like the most. Through time, as I got more experienced, I learned that there is a lot more behind just designing graphic user interface.</p><p>Now my goal is to design digital products that are intuitive and easy to use, as I really try to put myself in the users' shoes and try to understand where there are pain points and where they will encounter moments of delight. I achieve this with good research and concept iterations before starting to design, and after I also want to verify the idea with a clickable prototype.</p><p>If I am not at work or home, I am usually on a long walk with my young crazy black Labrador retriever, playing basketball or riding my mountain bike somewhere in the woods. Oh, but if it's Friday evening... then I am usually drinking a beer or two and dancing to house or drum and bass music.</p> ",
    gitHub: null,
    twitter: null,
    stackOverflow: null,
    linkedIn: "/in/r0kh0r/",
    imagePortraitUrl: "https://i.1337co.de/profile/rok-horvat",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/rok-horvat",
    highlighted: false,
    published: true
  },
  {
    name: "Niklas Sjöberg",
    email: "niklas.sjoberg@1337.tech",
    phoneNumber: "+46735119828",
    office: "Helsingborg",
    manager: "jenny.fergeus@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>I've always been a person that's curious about how things work, and driven by acquiring new knowledge. This led me to study Information and Communication Engineering Technologies in Lund, a program that (depending on what master program you choose) combines human-computer interaction with programming. That's where I finally found my passion for writing code, and realized the almost endless possibilities that a programmer has.</p><p>For the last couple of years, I've worked as an iOS-developer within different business areas, and I very much enjoy creating usable mobile apps that are structured and based on well-known design patterns.</p><p>Outside of writing code, I've always had a huge interest in football, both as a player and a spectator. In my spare time you'll likely find me watching a game, thinking about the next move for my fantasy football team, or spending time with friends and family.</p> ",
    gitHub: "NickSjo",
    twitter: "Nilleeeee",
    stackOverflow: null,
    linkedIn: "/in/niklas-sjöberg-37b48371/",
    imagePortraitUrl: "https://i.1337co.de/profile/niklas-sjoberg",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/niklas-sjoberg",
    highlighted: false,
    published: true
  },
  {
    name: "Pontus Molin",
    email: "pontus.molin@1337.tech",
    phoneNumber: "+46725133799",
    office: "Lund",
    manager: "andreas.nilsson@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>I got my first taste of programming when I was about fifteen years old and very fond of playing computer games and I wanted to know how they worked and were made. So I looked around on the web and made a simple adventure game (with dragons!) for the terminal, using C++. Since then, programming has been one of my hobbies and now I finally get to do it professionally!</p><p>Among the technologies and programming languages I have tried I really enjoy web development. What I like the best about the web is that it is so easily available, anyone with a browser can access your product, and that includes all computers and smartphones. One of my favourite aspects of programming is the problem solving, I think it’s such a great feeling when you come up with the solution.</p><p>During my free time I like playing all kinds of games, computerised and not, with my friends. When it’s just me I tend to tinker with my hobby projects and they can involve anything from coding to 3D-printing or growing chillies or other plants that produce something tasty.</p> ",
    gitHub: "Poliky4",
    twitter: null,
    stackOverflow: null,
    linkedIn: "/in/pontus-molin-74350aa3/",
    imagePortraitUrl: "https://i.1337co.de/profile/pontus-molin",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/pontus-molin",
    highlighted: false,
    published: true
  },
  {
    name: "Preethi Srinivasan",
    email: "preethi.srinivasan@1337.tech",
    phoneNumber: "+46761133736",
    office: "Helsingborg",
    manager: "lotta.wennolf@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>I am a person with high goals and always passionate to learn new things and combine them in creative ways. I enjoy the new challenges that every project brings.</p><p>In my free time, I like traveling with my friends and family where I can collect beautiful memories. I also enjoy sharing thoughts with experienced people and learning from their experience. Even though I was born and raised in India, I love to explore & embrace different cultures and food. Gardening is my hobby. Being close to nature and its creation keeps me energetic and Happy.</p> ",
    gitHub: null,
    twitter: null,
    stackOverflow: null,
    linkedIn: "/in/preethi-srinivasan-b01534164/",
    imagePortraitUrl: "https://i.1337co.de/profile/preethi-srinivasan",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/preethi-srinivasan",
    highlighted: true,
    published: true
  },
  {
    name: "Raslav Milutinović",
    email: "raslav.milutinovic@1337.tech",
    phoneNumber: "+38640133719",
    office: "Ljubljana",
    manager: "biserka.cvetkovska@1337.tech",
    orgUnit: "/Employees",
    mainText: "<p>I am a full-stack developer with preference for backend.</p><p>I mostly program in Typescript and Python. I love using latest technologies such as server-less and exciting new databases like neo4j.</p><p>I love working on projects that solve problems at scale. I especially enjoy programming things that I would and might use in the future.</p> ",
    gitHub: "rasovica",
    twitter: null,
    stackOverflow: null,
    linkedIn: "/in/raslav-milutinovic/",
    imagePortraitUrl: "https://i.1337co.de/profile/raslav-milutinovic",
    imageWallOfLeetUrl: "https://i.1337co.de/wallofleet/raslav-milutinovic",
    highlighted: false,
    published: true
  }

]
